version: "3.5"

services:
    postgredb:
      container_name: postgres-palavra
      image: postgres
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=palavrat
      ports:
        - "81:5432"
    app:
      image: apptesteappsb:latest
      build:
        context: .
      container_name: app
      ports:
        - "80:8084"
      depends_on:
        - postgredb
